{
 "title": "Blackbox ICMP",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": "probe_success" },
   { "name": "team_id", "label": "team_id", "query": "label_values(instance)" },
   { "name": "problem_id", "label": "problem_id", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "All Node(ALL)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(probe_success)" }
   ]
  },
  {
   "title": "Alive Node(ALL)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(probe_success)" }
   ]
  },
  {
   "title": "All Node(Select)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(probe_success{instance=~\"$host\"})"
    },
    {}
   ]
  },
  {
   "title": "Alive Node(Select)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(probe_success{instance=~\"$host\"})"
    },
    {}
   ]
  },
  {
   "title": "ICMP Result(Select)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "probe_success{instance=~\"$host\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ICMP Result(ALL)",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "expr": "probe_success", "legendFormat": "{{instance}}" }
   ]
  }
 ]
}