apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:7.6.0
        env:
          - name: ELASTICSEARCH_URL
            value: http://elasticsearch:9200
          - name: SERVER_HOST
            value: "0.0.0.0"
        ports:
        - containerPort: 5601
        resources:
          limits:
            cpu: 1000m
            memory: 2000Mi
          requests:
            cpu: 500m
            memory: 1000Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: monitoring
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 5601
  selector:
    app: kibana
  type: LoadBalancer
