apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: stable
apiServer:
  certSANs:
  # - "LOAD_BALANCER_DNS"
  - 172.20.100.32
# controlPlaneEndpoint: "LOAD_BALANCER_DNS:LOAD_BALANCER_PORT"
controlPlaneEndpoint: "172.20.100.32:6443"
networking:
  podSubnet: 10.244.0.0/16
