apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging # テスト用
  namespace: cert-manager
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: hayatake396@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    dns01:
      providers:
      - name: cloudflare
        cloudflare:
          email: account@icttoracon.net
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod # 本番用
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: hayatake396@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    dns01:
      providers:
      - name: cloudflare
        cloudflare:
          email: account@icttoracon.net
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key
